server:
  port: 8080
spring:
  datasource:
    dynamic:
      #默认就是master可以不指定
      primary: master
      datasource:
        master:
#          url: jdbc:mysql://10.0.0.2:3306/hzzdev?useUnicode=true&characterEncoding=utf-8&useSSL=false
#          username: hzzwork
#          password: "@bgd5QoJtuYKrIih"
          url: jdbc:mysql://192.144.230.48:3306/hzzdev?useUnicode=true&characterEncoding=utf-8
          username: root
          password: 3eufds983d
#          driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 10.0.0.4
    port: 6379
    password: work:3eufds983d

  #spring session使用存储类型，默认就是redis所以可以省略
  session:
    store-type: redis
    redis:
        flush-mode: on_save